[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmd = "npm ci --include=optional"

[phases.build]
cmd = "npm run build"

[start]
cmd = "npm start"

[variables]
SHARP_IGNORE_GLOBAL_LIBVIPS = "1"